### ISSUE TITLE
Re-visit the way zoom buttons are moved

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#298]
We want to change the way the zoom buttons are being moved, we implement a hack here.
https://github.com/GlobalFishingWatch/pelagos-client/pull/297

**Comment by redhog** [comment]
I suggest not moving the button. There really isn't a good way to do this - there is no class or id on the button, or any surrounding divs.

**Comment by enriquetuya** [comment]
@redhog have you tried out the API?
https://developers.google.com/maps/documentation/javascript/examples/control-positioning
https://developers.google.com/maps/documentation/javascript/reference#ControlPosition LT or LC could work.

**Comment by jarmstrongbts** [comment]
There seems to be no way to reliably call the map zoom buttons. Google makes it very hard by not giving you unique ids or classes to grab. You can't grab the title of the zoom button, because it may change based on language selected by the user. You can't grab the image filename, because it changes based on dpi. I don't love the idea of having the map buttons at left center, but if we can't move the GFW logo a little to the right, I think it's probably the best option.
