### ISSUE TITLE
Feature request: Vessel tracks in separate blade

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/pelagos-client#385]
Display vessel track animations in a separate blade in the sidebar ("Vessel tracks"? Better more generic name?)

Implementation idea: Animations can have a category (a string value). If at least one animation exists withing a certain category, a new blade is created with that name, holding a SimpleLayerList instance filtering for that category.

Separated out of https://github.com/GlobalFishingWatch/pelagos-client/issues/346

**Comment by redhog** [comment]
SimpleLayerList.prototype.AnimationWidget.prototype.baseClass
    "SimpleLayerList-AnimationWidget"
    declare("X", [SimpleLayerList.prototype.AnimationWidget], {}).prototype.baseClass
    "AnimationListBase-AnimationWidget"

but

    A = declare("A", [], {X: 1})
    B = declare("B", [A], {X: 2})
    declare("C", [B], {Y: 0}).prototype.X
    2

**Comment by enriquetuya** [comment]
To test:
- Go to advanced mode
- Go to edit mode
- Expand one of the animations
- Click on the [empty] value right of "Category:"
- Enter a new category name
- Press enter

The animation should now be moved to a new tab with the name you entered.

**Comment by enriquetuya** [comment]
@redhog 
- [x] the PR has conflicts: https://github.com/GlobalFishingWatch/pelagos-client/pull/389 Conflicting files: 
  `js/app/Visualization/UI/SidePanels/SimpleLayerList.js`
- ~~[ ] We need to change something on the functionality, when you create a category, you have the blade with that category only when you have at least one animation selected. For example, if you set the `Vessels` clategory for a Vessel Track the `Vessels` blade only appear if you have a track selected, if not the vessels blade disappear. We need to display the blade always once the category is set, if not the UX feels weird since the blade appears and dissapears in a non very elegant way.~~
  - Too complicated to do given current implementation

**Comment by enriquetuya** [comment]
Setting as blocker since I can't test this out.

**Comment by enriquetuya** [comment]
@redhog I'm trying the categorized blades and I am not being able to get the vessels selected after I have set the category to be included on the `VESSELS` category.

MY steps:
1- load map
2- select vessel
3- `ctrl alt a` and go to config
4- expand vessel track configuration
5- set category to `vessels`
6- switch to non editing view
7- save track
8- select another track, it appears on the `layers` blade.

**Comment by redhog** [comment]
This should work now :)
